[LOGGING]
level="DEBUG"
[LOGGING.logFileConfigs]
logPath="./logs"
fileName="mailerlogs"

[DB]
[DB.clientOptions]
server="127.0.0.1"
port=27017
authDatabase="admin"
database="etDB"
userName="etDBUser"
password="etDBUser"

